# Generated by Django 6.0.5 on 2026-06-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_delete_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='capacity',
        ),
        migrations.AddField(
            model_name='airplane',
            name='rows',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airplane',
            name='seats_per_row',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
