# Generated by Django 6.0.5 on 2026-06-07 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airports", "0003_remove_airplane_capacity_airplane_rows_and_more"),
        ("tickets", "0003_alter_ticket_seat_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ticket",
            name="reserved_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("flight", "seat_number"),
                name="uniq_active_seat_per_flight",
            ),
        ),
    ]
