# Generated by Django 6.0.5 on 2026-06-22 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        (
            "tickets",
            "0004_alter_ticket_unique_together_ticket_reserved_until_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="orders.order",
            ),
        ),
    ]
