# Generated by Django 6.0.5 on 2026-06-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_ticket_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="reserved_until",
        ),
    ]
