# Generated by Django 6.0.5 on 2026-06-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reserved_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
